version: "3"

services:
  cryptogateway.api:
    image: cryptogateway.api
    container_name: api
    build:
      context: .
      dockerfile: src/CryptoGateway.API/Dockerfile
    ports:
      - 8500:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: "Y"